[package]
name = "qubit-collections"
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-collections"
description = "Custom collection types for specialized access and traversal patterns"
homepage = "https://github.com/qubit-ltd/rs-collections"
documentation = "https://docs.rs/qubit-collections"
readme = "README.md"
keywords = ["collections", "index", "ordered", "map", "qubit"]
categories = ["data-structures"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/src/**",
    "/tests/**",
    "/benches/**",
]

[lib]
name = "qubit_collections"
doctest = true

[dependencies]
hashbrown = { version = "0.17", default-features = false }

[dev-dependencies]
criterion = { version = "0.8", default-features = false }

[[bench]]
name = "ordered_index_map"
path = "benches/map/ordered_index_map.rs"
harness = false
